fix: GithubActionsでのテスト実行方法変更

diff --git a/.github/workflows/auto_test.yml b/.github/workflows/auto_test.yml
--- a/.github/workflows/auto_test.yml
+++ b/.github/workflows/auto_test.yml
@@ -66,12 +66,20 @@ jobs:
           EOF
       - name: Check if .env file exists
         run: |
-          cat ./docker/test/.env | head -n 1
+          FILE="./docker/test/.env"
+          if [ ! -f $FILE ]
+            echo ".env is not found"
+            exit 1
+          elif [ ! -s $FILE ]; then
+            echo ".env is empty"
+            exit 1
+          fi
       # docker composeでなく docker-composeを使わなといけない。
       # https://github.com/actions/runner-images/issues/5022#issuecomment-1030025608
-      - name: Create docker containers and execute test
+      - name: Create docker containers
         run: |
-          docker-compose -f ./docker/test/compose.yaml up -d
-      - name: Check app container logs
+          docker compose -f ./docker/test/compose.yaml up -d
+      - name: Execute maven test
         run: |
-          docker-compose -f ./docker/test/compose.yaml logs --tail 10 app
+          docker compose exec -it app /bin/bash
+          ./mvnw test
